import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'region_provider.dart';

class AppStrings {
  final String whatAreYouLookingFor;
  final String currentPrice;
  final String target;
  final String catchNow;
  final String safeShop;
  final String themeSkin;
  final String accountInfo;
  final String guestUser;
  final String radar;
  final String premium;
  final String profile;
  final String profileSettings;
  final String regionLanguage;
  final String loginRegister;
  final String searching;
  final String warning;
  final String loginRequired;
  final String cancel;
  final String login;
  final String openingLink;
  final String showingAd;
  final String youArePro;
  final String unlockPro;
  final String proFeatures;
  final String subscribeMonthly;
  final String subscribeYearly;
  final String alertDetails;
  final String alertDetailsContent;
  final String notifications;
  final String immediateAlerts;
  final String immediateAlertsDesc;
  final String dailySummary;
  final String dailySummaryDesc;
  final String summaryTime;

  AppStrings({
    required this.whatAreYouLookingFor,
    required this.currentPrice,
    required this.target,
    required this.catchNow,
    required this.safeShop,
    required this.themeSkin,
    required this.accountInfo,
    required this.guestUser,
    required this.radar,
    required this.premium,
    required this.profile,
    required this.profileSettings,
    required this.regionLanguage,
    required this.loginRegister,
    required this.searching,
    required this.warning,
    required this.loginRequired,
    required this.cancel,
    required this.login,
    required this.openingLink,
    required this.showingAd,
    required this.youArePro,
    required this.unlockPro,
    required this.proFeatures,
    required this.subscribeMonthly,
    required this.subscribeYearly,
    required this.alertDetails,
    required this.alertDetailsContent,
    required this.notifications,
    required this.immediateAlerts,
    required this.immediateAlertsDesc,
    required this.dailySummary,
    required this.dailySummaryDesc,
    required this.summaryTime,
  });
}

final Map<String, AppStrings> _translations = {
  'en': AppStrings(
    whatAreYouLookingFor: 'What are you looking for?',
    currentPrice: 'Current Price',
    target: 'Target',
    catchNow: 'Catch now',
    safeShop: 'Safe Shop',
    themeSkin: 'Theme Skin',
    accountInfo: 'Account Info',
    guestUser: 'Guest User',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profile',
    profileSettings: 'Profile & Settings',
    regionLanguage: 'Region & Language',
    loginRegister: 'Login or register to sync your tracking.',
    searching: 'Searching...',
    warning: 'Warning',
    loginRequired: 'Login Required',
    cancel: 'Cancel',
    login: 'Login',
    openingLink: 'Opening Affiliate Link...',
    showingAd: 'Showing Interstitial Ad...',
    youArePro: 'You are on PRO Plan! 🎉',
    unlockPro: 'Unlock PRO Features',
    proFeatures: '• Track unlimited items (FREE: 3/mo)\n• Items never expire (FREE: 30 days)\n• Zero Ads',
    subscribeMonthly: 'Subscribe 5.99 PLN / mo',
    subscribeYearly: 'Yearly Plan 49.99 PLN / yr',
    alertDetails: 'Alert Details',
    alertDetailsContent: 'Product and Alert details will be displayed here.',
    notifications: 'Notifications',
    immediateAlerts: 'Immediate Alerts',
    immediateAlertsDesc: 'Notify me as soon as the price drops',
    dailySummary: 'Daily Summary',
    dailySummaryDesc: 'Receive a daily report of price changes',
    summaryTime: 'Summary Time',
  ),
  'pl': AppStrings(
    whatAreYouLookingFor: 'Czego szukasz?',
    currentPrice: 'Obecna Cena',
    target: 'Cel',
    catchNow: 'Złap teraz',
    safeShop: 'Bezpieczny Sklep',
    themeSkin: 'Wygląd',
    accountInfo: 'Informacje o Koncie',
    guestUser: 'Konto Gościa',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Profil i Ustawienia',
    regionLanguage: 'Region i Język',
    loginRegister: 'Zaloguj lub zarejestruj, aby synchronizować.',
    searching: 'Wyszukiwanie...',
    warning: 'Ostrzeżenie',
    loginRequired: 'Wymagane Logowanie',
    cancel: 'Anuluj',
    login: 'Zaloguj',
    openingLink: 'Otwieranie linku...',
    showingAd: 'Wyświetlanie reklamy...',
    youArePro: 'Masz plan PRO! 🎉',
    unlockPro: 'Odblokuj funkcje PRO',
    proFeatures: '• Śledź bez limitu (FREE: 3/mc)\n• Przedmioty nie wygasają (FREE: 30 dni)\n• Brak reklam',
    subscribeMonthly: 'Subskrybuj 5.99 PLN / mc',
    subscribeYearly: 'Plan roczny 49.99 PLN / rok',
    alertDetails: 'Szczegóły Alertu',
    alertDetailsContent: 'Szczegóły produktu i alertu.',
    notifications: 'Powiadomienia',
    immediateAlerts: 'Natychmiastowe Alerty',
    immediateAlertsDesc: 'Powiadom od razu, gdy cena spadnie',
    dailySummary: 'Codzienne Podsumowanie',
    dailySummaryDesc: 'Otrzymuj codzienny raport zmian cen',
    summaryTime: 'Godzina podsumowania',
  ),
  'de': AppStrings(
    whatAreYouLookingFor: 'Was suchst du?',
    currentPrice: 'Aktueller Preis',
    target: 'Ziel',
    catchNow: 'Jetzt schnappen',
    safeShop: 'Sicherer Shop',
    themeSkin: 'Design',
    accountInfo: 'Kontoinformationen',
    guestUser: 'Gastnutzer',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Profil & Einstellungen',
    regionLanguage: 'Region & Sprache',
    loginRegister: 'Anmelden zum Synchronisieren.',
    searching: 'Suchen...',
    warning: 'Warnung',
    loginRequired: 'Anmeldung erforderlich',
    cancel: 'Abbrechen',
    login: 'Anmelden',
    openingLink: 'Link wird geöffnet...',
    showingAd: 'Werbung wird angezeigt...',
    youArePro: 'Du hast den PRO-Plan! 🎉',
    unlockPro: 'PRO-Funktionen freischalten',
    proFeatures: '• Unbegrenzt verfolgen\n• Läuft nicht ab\n• Keine Werbung',
    subscribeMonthly: 'Abonnieren 5.99 PLN / Monat',
    subscribeYearly: 'Jahresplan 49.99 PLN / Jahr',
    alertDetails: 'Alarmdetails',
    alertDetailsContent: 'Produkt- und Alarmdetails hier.',
    notifications: 'Benachrichtigungen',
    immediateAlerts: 'Sofortige Warnungen',
    immediateAlertsDesc: 'Benachrichtigen sobald der Preis sinkt',
    dailySummary: 'Tägliche Zusammenfassung',
    dailySummaryDesc: 'Erhalten Sie einen täglichen Bericht',
    summaryTime: 'Zusammenfassungszeit',
  ),
  'fr': AppStrings(
    whatAreYouLookingFor: 'Que cherchez-vous ?',
    currentPrice: 'Prix Actuel',
    target: 'Cible',
    catchNow: 'Attraper',
    safeShop: 'Boutique Sûre',
    themeSkin: 'Thème',
    accountInfo: 'Infos du Compte',
    guestUser: 'Invité',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Profil & Paramètres',
    regionLanguage: 'Région & Langue',
    loginRegister: 'Connectez-vous.',
    searching: 'Recherche...',
    warning: 'Avertissement',
    loginRequired: 'Connexion requise',
    cancel: 'Annuler',
    login: 'Connexion',
    openingLink: 'Ouverture du lien...',
    showingAd: 'Affichage de la publicité...',
    youArePro: 'Vous avez le plan PRO ! 🎉',
    unlockPro: 'Débloquer PRO',
    proFeatures: '• Suivi illimité\n• N expire jamais\n• Sans pub',
    subscribeMonthly: 'S abonner 5.99 PLN / mois',
    subscribeYearly: 'Plan annuel 49.99 PLN / an',
    alertDetails: 'Détails de l alerte',
    alertDetailsContent: 'Détails du produit.',
    notifications: 'Notifications',
    immediateAlerts: 'Alertes immédiates',
    immediateAlertsDesc: 'M informer dès que le prix baisse',
    dailySummary: 'Résumé quotidien',
    dailySummaryDesc: 'Recevez un rapport quotidien',
    summaryTime: 'Heure du résumé',
  ),
  'it': AppStrings(
    whatAreYouLookingFor: 'Cosa stai cercando?',
    currentPrice: 'Prezzo Attuale',
    target: 'Obiettivo',
    catchNow: 'Prendi ora',
    safeShop: 'Negozio Sicuro',
    themeSkin: 'Tema',
    accountInfo: 'Info Account',
    guestUser: 'Ospite',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profilo',
    profileSettings: 'Profilo e Impostazioni',
    regionLanguage: 'Regione e Lingua',
    loginRegister: 'Accedi per sincronizzare.',
    searching: 'Ricerca...',
    warning: 'Avvertimento',
    loginRequired: 'Accesso richiesto',
    cancel: 'Annulla',
    login: 'Accedi',
    openingLink: 'Apertura link...',
    showingAd: 'Mostrando annuncio...',
    youArePro: 'Sei nel piano PRO! 🎉',
    unlockPro: 'Sblocca PRO',
    proFeatures: '• Tracciamento illimitato\n• Nessuna scadenza\n• Niente pubblicità',
    subscribeMonthly: 'Abbonati 5.99 PLN / mese',
    subscribeYearly: 'Piano annuale 49.99 PLN / anno',
    alertDetails: 'Dettagli Avviso',
    alertDetailsContent: 'Dettagli qui.',
    notifications: 'Notifiche',
    immediateAlerts: 'Avvisi immediati',
    immediateAlertsDesc: 'Avvisami appena il prezzo scende',
    dailySummary: 'Riepilogo giornaliero',
    dailySummaryDesc: 'Ricevi un rapporto giornaliero',
    summaryTime: 'Ora del riepilogo',
  ),
  'es': AppStrings(
    whatAreYouLookingFor: '¿Qué estás buscando?',
    currentPrice: 'Precio Actual',
    target: 'Objetivo',
    catchNow: 'Atrapar ahora',
    safeShop: 'Tienda Segura',
    themeSkin: 'Tema',
    accountInfo: 'Info de Cuenta',
    guestUser: 'Invitado',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Perfil',
    profileSettings: 'Perfil y Configuración',
    regionLanguage: 'Región e Idioma',
    loginRegister: 'Inicia sesión.',
    searching: 'Buscando...',
    warning: 'Advertencia',
    loginRequired: 'Inicio de sesión requerido',
    cancel: 'Cancelar',
    login: 'Entrar',
    openingLink: 'Abriendo enlace...',
    showingAd: 'Mostrando anuncio...',
    youArePro: '¡Estás en el plan PRO! 🎉',
    unlockPro: 'Desbloquear PRO',
    proFeatures: '• Seguimiento ilimitado\n• No expira\n• Sin anuncios',
    subscribeMonthly: 'Suscribirse 5.99 PLN / mes',
    subscribeYearly: 'Plan anual 49.99 PLN / año',
    alertDetails: 'Detalles de la alerta',
    alertDetailsContent: 'Detalles aquí.',
    notifications: 'Notificaciones',
    immediateAlerts: 'Alertas Inmediatas',
    immediateAlertsDesc: 'Notificar en cuanto baje el precio',
    dailySummary: 'Resumen Diario',
    dailySummaryDesc: 'Recibir un informe diario',
    summaryTime: 'Hora del resumen',
  ),
  'no': AppStrings(
    whatAreYouLookingFor: 'Hva ser du etter?',
    currentPrice: 'Nåværende pris',
    target: 'Mål',
    catchNow: 'Fang nå',
    safeShop: 'Trygg Butikk',
    themeSkin: 'Tema',
    accountInfo: 'Kontoinfo',
    guestUser: 'Gjest',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Profil og Innstillinger',
    regionLanguage: 'Region og Språk',
    loginRegister: 'Logg inn for å synkronisere.',
    searching: 'Søker...',
    warning: 'Advarsel',
    loginRequired: 'Innlogging kreves',
    cancel: 'Avbryt',
    login: 'Logg inn',
    openingLink: 'Åpner lenke...',
    showingAd: 'Viser annonse...',
    youArePro: 'Du har PRO-plan! 🎉',
    unlockPro: 'Lås opp PRO',
    proFeatures: '• Ubegrenset sporing\n• Utløper aldri\n• Ingen annonser',
    subscribeMonthly: 'Abonner 5.99 PLN / mnd',
    subscribeYearly: 'Årsplan 49.99 PLN / år',
    alertDetails: 'Varseldetaljer',
    alertDetailsContent: 'Detaljer her.',
    notifications: 'Varsler',
    immediateAlerts: 'Umiddelbare Varsler',
    immediateAlertsDesc: 'Varsle meg så snart prisen synker',
    dailySummary: 'Daglig Sammendrag',
    dailySummaryDesc: 'Motta en daglig rapport om prisendringer',
    summaryTime: 'Oppsummeringstid',
  ),
  'is': AppStrings(
    whatAreYouLookingFor: 'Eftir hverju ertu að leita?',
    currentPrice: 'Verð',
    target: 'Markmið',
    catchNow: 'Grípa',
    safeShop: 'Örugg',
    themeSkin: 'Þema',
    accountInfo: 'Reikningur',
    guestUser: 'Gestur',
    radar: 'Ratsjá',
    premium: 'Úrvals',
    profile: 'Prófíll',
    profileSettings: 'Stillingar',
    regionLanguage: 'Tungumál',
    loginRegister: 'Skráðu þig inn.',
    searching: 'Leita...',
    warning: 'Viðvörun',
    loginRequired: 'Innskráning nauðsynleg',
    cancel: 'Hætta við',
    login: 'Innskrá',
    openingLink: 'Opna tengil...',
    showingAd: 'Sýni auglýsingu...',
    youArePro: 'Þú ert með PRO! 🎉',
    unlockPro: 'Opna PRO',
    proFeatures: '• Ótakmarkað\n• Rennur ekki út\n• Engar auglýsingar',
    subscribeMonthly: 'Áskrift 5.99 PLN / mán',
    subscribeYearly: 'Ársáskrift 49.99 PLN / ár',
    alertDetails: 'Nánar',
    alertDetailsContent: 'Upplýsingar hér.',
    notifications: 'Tilkynningar',
    immediateAlerts: 'Strax Tilkynningar',
    immediateAlertsDesc: 'Tilkynna þegar verð lækkar',
    dailySummary: 'Dagleg Yfirlit',
    dailySummaryDesc: 'Fá daglega skýrslu um verðbreytingar',
    summaryTime: 'Tími yfirlits',
  ),
  'uk': AppStrings(
    whatAreYouLookingFor: 'Що ви шукаєте?',
    currentPrice: 'Поточна ціна',
    target: 'Ціль',
    catchNow: 'Зловити',
    safeShop: 'Безпечний',
    themeSkin: 'Тема',
    accountInfo: 'Акаунт',
    guestUser: 'Гість',
    radar: 'Радар',
    premium: 'Преміум',
    profile: 'Профіль',
    profileSettings: 'Налаштування',
    regionLanguage: 'Мова',
    loginRegister: 'Увійдіть.',
    searching: 'Пошук...',
    warning: 'Попередження',
    loginRequired: 'Потрібен вхід',
    cancel: 'Скасувати',
    login: 'Увійти',
    openingLink: 'Відкриття посилання...',
    showingAd: 'Показ реклами...',
    youArePro: 'У вас PRO план! 🎉',
    unlockPro: 'Розблокувати PRO',
    proFeatures: '• Безліміт\n• Не зникає\n• Без реклами',
    subscribeMonthly: 'Підписка 5.99 PLN / міс',
    subscribeYearly: 'Річний план 49.99 PLN / рік',
    alertDetails: 'Деталі',
    alertDetailsContent: 'Інформація тут.',
    notifications: 'Сповіщення',
    immediateAlerts: 'Миттєві сповіщення',
    immediateAlertsDesc: 'Сповіщати, щойно ціна знизиться',
    dailySummary: 'Щоденний підсумок',
    dailySummaryDesc: 'Отримувати щоденний звіт про ціни',
    summaryTime: 'Час підсумку',
  ),
  'nl': AppStrings(
    whatAreYouLookingFor: 'Waar ben je naar op zoek?',
    currentPrice: 'Prijs',
    target: 'Doel',
    catchNow: 'Nu vangen',
    safeShop: 'Veilige Winkel',
    themeSkin: 'Thema',
    accountInfo: 'Account',
    guestUser: 'Gast',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profiel',
    profileSettings: 'Instellingen',
    regionLanguage: 'Regio & Taal',
    loginRegister: 'Log in.',
    searching: 'Zoeken...',
    warning: 'Waarschuwing',
    loginRequired: 'Inloggen vereist',
    cancel: 'Annuleren',
    login: 'Log in',
    openingLink: 'Link openen...',
    showingAd: 'Advertentie tonen...',
    youArePro: 'Je hebt PRO! 🎉',
    unlockPro: 'Ontgrendel PRO',
    proFeatures: '• Onbeperkt volgen\n• Verloopt nooit\n• Geen advertenties',
    subscribeMonthly: 'Abonneren 5.99 PLN / mnd',
    subscribeYearly: 'Jaarplan 49.99 PLN / jaar',
    alertDetails: 'Details',
    alertDetailsContent: 'Informatie hier.',
    notifications: 'Meldingen',
    immediateAlerts: 'Onmiddellijke Meldingen',
    immediateAlertsDesc: 'Melden zodra de prijs daalt',
    dailySummary: 'Dagelijks Overzicht',
    dailySummaryDesc: 'Ontvang een dagelijks prijzenrapport',
    summaryTime: 'Overzichtstijd',
  ),
  'cs': AppStrings(
    whatAreYouLookingFor: 'Co hledáte?',
    currentPrice: 'Cena',
    target: 'Cíl',
    catchNow: 'Chytit',
    safeShop: 'Bezpečný obchod',
    themeSkin: 'Téma',
    accountInfo: 'Účet',
    guestUser: 'Host',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Nastavení',
    regionLanguage: 'Jazyk',
    loginRegister: 'Přihlaste se.',
    searching: 'Hledání...',
    warning: 'Varování',
    loginRequired: 'Nutné přihlášení',
    cancel: 'Zrušit',
    login: 'Přihlásit',
    openingLink: 'Otevírání odkazu...',
    showingAd: 'Zobrazování reklamy...',
    youArePro: 'Máte plán PRO! 🎉',
    unlockPro: 'Odemknout PRO',
    proFeatures: '• Neomezené sledování\n• Nikdy nevyprší\n• Bez reklam',
    subscribeMonthly: 'Předplatit 5.99 PLN / měs',
    subscribeYearly: 'Roční plán 49.99 PLN / rok',
    alertDetails: 'Detaily upozornění',
    alertDetailsContent: 'Detaily zde.',
    notifications: 'Upozornění',
    immediateAlerts: 'Okamžitá Upozornění',
    immediateAlertsDesc: 'Upozornit, jakmile cena klesne',
    dailySummary: 'Denní Souhrn',
    dailySummaryDesc: 'Získejte denní přehled změn cen',
    summaryTime: 'Čas souhrnu',
  ),
  'sk': AppStrings(
    whatAreYouLookingFor: 'Čo hľadáte?',
    currentPrice: 'Cena',
    target: 'Cieľ',
    catchNow: 'Chytiť',
    safeShop: 'Bezpečný',
    themeSkin: 'Téma',
    accountInfo: 'Účet',
    guestUser: 'Hosť',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Nastavenia',
    regionLanguage: 'Jazyk',
    loginRegister: 'Prihláste sa.',
    searching: 'Hľadanie...',
    warning: 'Varovanie',
    loginRequired: 'Vyžaduje sa prihlásenie',
    cancel: 'Zrušiť',
    login: 'Prihlásiť',
    openingLink: 'Otváranie odkazu...',
    showingAd: 'Zobrazuje sa reklama...',
    youArePro: 'Máte plán PRO! 🎉',
    unlockPro: 'Odomknúť PRO',
    proFeatures: '• Neobmedzené sledovanie\n• Nikdy nevyprší\n• Bez reklám',
    subscribeMonthly: 'Predplatiť 5.99 PLN / mes',
    subscribeYearly: 'Ročný plán 49.99 PLN / rok',
    alertDetails: 'Detaily',
    alertDetailsContent: 'Detaily tu.',
    notifications: 'Upozornenia',
    immediateAlerts: 'Okamžité Upozornenia',
    immediateAlertsDesc: 'Upozorniť, hneď ako cena klesne',
    dailySummary: 'Denný Súhrn',
    dailySummaryDesc: 'Získajte denný prehľad zmien cien',
    summaryTime: 'Čas súhrnu',
  ),
  'sv': AppStrings(
    whatAreYouLookingFor: 'Sök',
    currentPrice: 'Pris',
    target: 'Mål',
    catchNow: 'Fånga',
    safeShop: 'Säker',
    themeSkin: 'Tema',
    accountInfo: 'Konto',
    guestUser: 'Gäst',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Inställningar',
    regionLanguage: 'Språk',
    loginRegister: 'Logga in.',
    searching: 'Söker...',
    warning: 'Varning',
    loginRequired: 'Inloggning krävs',
    cancel: 'Avbryt',
    login: 'Logga in',
    openingLink: 'Öppnar länk...',
    showingAd: 'Visar annons...',
    youArePro: 'Du har PRO! 🎉',
    unlockPro: 'Lås upp PRO',
    proFeatures: '• Obegränsat\n• Löper inte ut\n• Inga annonser',
    subscribeMonthly: 'Prenumerera 5.99 PLN / mån',
    subscribeYearly: 'Årsplan 49.99 PLN / år',
    alertDetails: 'Detaljer',
    alertDetailsContent: 'Information här.',
    notifications: 'Aviseringar',
    immediateAlerts: 'Direkta Aviseringar',
    immediateAlertsDesc: 'Meddela mig när priset sjunker',
    dailySummary: 'Daglig Sammanfattning',
    dailySummaryDesc: 'Få en daglig rapport om priser',
    summaryTime: 'Sammanfattningstid',
  ),
  'da': AppStrings(
    whatAreYouLookingFor: 'Søg',
    currentPrice: 'Pris',
    target: 'Mål',
    catchNow: 'Fang',
    safeShop: 'Sikker',
    themeSkin: 'Tema',
    accountInfo: 'Konto',
    guestUser: 'Gæst',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Indstillinger',
    regionLanguage: 'Sprog',
    loginRegister: 'Log ind.',
    searching: 'Søger...',
    warning: 'Advarsel',
    loginRequired: 'Login påkrævet',
    cancel: 'Annuller',
    login: 'Log ind',
    openingLink: 'Åbner link...',
    showingAd: 'Viser annonce...',
    youArePro: 'Du har PRO! 🎉',
    unlockPro: 'Lås PRO op',
    proFeatures: '• Ubegrænset\n• Udløber aldrig\n• Ingen annoncer',
    subscribeMonthly: 'Abonner 5.99 PLN / mdr',
    subscribeYearly: 'Årsplan 49.99 PLN / år',
    alertDetails: 'Detaljer',
    alertDetailsContent: 'Information her.',
    notifications: 'Notifikationer',
    immediateAlerts: 'Øjeblikkelige Notifikationer',
    immediateAlertsDesc: 'Giv besked når prisen falder',
    dailySummary: 'Daglig Opsummering',
    dailySummaryDesc: 'Få en daglig prisrapport',
    summaryTime: 'Opsummeringstid',
  ),
  'fi': AppStrings(
    whatAreYouLookingFor: 'Etsi',
    currentPrice: 'Hinta',
    target: 'Tavoite',
    catchNow: 'Nappaa',
    safeShop: 'Turvallinen',
    themeSkin: 'Teema',
    accountInfo: 'Tili',
    guestUser: 'Vieras',
    radar: 'Tutka',
    premium: 'Premium',
    profile: 'Profiili',
    profileSettings: 'Asetukset',
    regionLanguage: 'Kieli',
    loginRegister: 'Kirjaudu.',
    searching: 'Etsitään...',
    warning: 'Varoitus',
    loginRequired: 'Kirjautuminen vaaditaan',
    cancel: 'Peruuta',
    login: 'Kirjaudu',
    openingLink: 'Avataan linkki...',
    showingAd: 'Näytetään mainos...',
    youArePro: 'Sinulla on PRO! 🎉',
    unlockPro: 'Avaa PRO',
    proFeatures: '• Rajoittamaton\n• Ei vanhene\n• Ei mainoksia',
    subscribeMonthly: 'Tilaa 5.99 PLN / kk',
    subscribeYearly: 'Vuosipaketti 49.99 PLN / vuosi',
    alertDetails: 'Tiedot',
    alertDetailsContent: 'Tiedot täällä.',
    notifications: 'Ilmoitukset',
    immediateAlerts: 'Välittömät Ilmoitukset',
    immediateAlertsDesc: 'Ilmoita heti kun hinta laskee',
    dailySummary: 'Päivittäinen Yhteenveto',
    dailySummaryDesc: 'Saa päivittäinen hintaraportti',
    summaryTime: 'Yhteenvedon aika',
  ),
  'pt': AppStrings(
    whatAreYouLookingFor: 'Procurar',
    currentPrice: 'Preço',
    target: 'Alvo',
    catchNow: 'Pegar',
    safeShop: 'Seguro',
    themeSkin: 'Tema',
    accountInfo: 'Conta',
    guestUser: 'Visitante',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Perfil',
    profileSettings: 'Configurações',
    regionLanguage: 'Idioma',
    loginRegister: 'Entrar.',
    searching: 'Procurando...',
    warning: 'Aviso',
    loginRequired: 'Login necessário',
    cancel: 'Cancelar',
    login: 'Entrar',
    openingLink: 'Abrindo link...',
    showingAd: 'Mostrando anúncio...',
    youArePro: 'Você tem o plano PRO! 🎉',
    unlockPro: 'Desbloquear PRO',
    proFeatures: '• Ilimitado\n• Nunca expira\n• Sem anúncios',
    subscribeMonthly: 'Assinar 5.99 PLN / mês',
    subscribeYearly: 'Plano Anual 49.99 PLN / ano',
    alertDetails: 'Detalhes',
    alertDetailsContent: 'Informações aqui.',
    notifications: 'Notificações',
    immediateAlerts: 'Alertas Imediatos',
    immediateAlertsDesc: 'Notificar assim que o preço cair',
    dailySummary: 'Resumo Diário',
    dailySummaryDesc: 'Receber um relatório diário',
    summaryTime: 'Hora do resumo',
  ),
  'el': AppStrings(
    whatAreYouLookingFor: 'Αναζήτηση',
    currentPrice: 'Τιμή',
    target: 'Στόχος',
    catchNow: 'Πιάσε',
    safeShop: 'Ασφαλές',
    themeSkin: 'Θέμα',
    accountInfo: 'Λογαριασμός',
    guestUser: 'Επισκέπτης',
    radar: 'Ραντάρ',
    premium: 'Premium',
    profile: 'Προφίλ',
    profileSettings: 'Ρυθμίσεις',
    regionLanguage: 'Γλώσσα',
    loginRegister: 'Σύνδεση.',
    searching: 'Αναζήτηση...',
    warning: 'Προειδοποίηση',
    loginRequired: 'Απαιτείται Σύνδεση',
    cancel: 'Ακύρωση',
    login: 'Σύνδεση',
    openingLink: 'Άνοιγμα συνδέσμου...',
    showingAd: 'Εμφάνιση διαφήμισης...',
    youArePro: 'Είστε στο PRO! 🎉',
    unlockPro: 'Ξεκλείδωμα PRO',
    proFeatures: '• Απεριόριστα\n• Χωρίς λήξη\n• Χωρίς διαφημίσεις',
    subscribeMonthly: 'Εγγραφή 5.99 PLN / μήνα',
    subscribeYearly: 'Ετήσιο 49.99 PLN / έτος',
    alertDetails: 'Λεπτομέρειες',
    alertDetailsContent: 'Πληροφορίες εδώ.',
    notifications: 'Ειδοποιήσεις',
    immediateAlerts: 'Άμεσες Ειδοποιήσεις',
    immediateAlertsDesc: 'Ειδοποίηση όταν πέσει η τιμή',
    dailySummary: 'Ημερήσια Σύνοψη',
    dailySummaryDesc: 'Λήψη ημερήσιας αναφοράς',
    summaryTime: 'Ώρα σύνοψης',
  ),
  'hu': AppStrings(
    whatAreYouLookingFor: 'Keresés',
    currentPrice: 'Ár',
    target: 'Cél',
    catchNow: 'Elkapni',
    safeShop: 'Biztonságos',
    themeSkin: 'Téma',
    accountInfo: 'Fiók',
    guestUser: 'Vendég',
    radar: 'Radar',
    premium: 'Prémium',
    profile: 'Profil',
    profileSettings: 'Beállítások',
    regionLanguage: 'Nyelv',
    loginRegister: 'Belépés.',
    searching: 'Keresés...',
    warning: 'Figyelmeztetés',
    loginRequired: 'Bejelentkezés szükséges',
    cancel: 'Mégse',
    login: 'Belépés',
    openingLink: 'Link megnyitása...',
    showingAd: 'Hirdetés megjelenítése...',
    youArePro: 'PRO csomagod van! 🎉',
    unlockPro: 'PRO feloldása',
    proFeatures: '• Korlátlan\n• Sosem jár le\n• Nincs hirdetés',
    subscribeMonthly: 'Feliratkozás 5.99 PLN / hó',
    subscribeYearly: 'Éves terv 49.99 PLN / év',
    alertDetails: 'Részletek',
    alertDetailsContent: 'Információk itt.',
    notifications: 'Értesítések',
    immediateAlerts: 'Azonnali Értesítések',
    immediateAlertsDesc: 'Értesítsen, amint az ár csökken',
    dailySummary: 'Napi Összefoglaló',
    dailySummaryDesc: 'Kapjon egy napi árjelentést',
    summaryTime: 'Összefoglaló ideje',
  ),
  'ro': AppStrings(
    whatAreYouLookingFor: 'Căutare',
    currentPrice: 'Preț',
    target: 'Țintă',
    catchNow: 'Prinde',
    safeShop: 'Sigur',
    themeSkin: 'Temă',
    accountInfo: 'Cont',
    guestUser: 'Oaspete',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Setări',
    regionLanguage: 'Limbă',
    loginRegister: 'Conectare.',
    searching: 'Căutare...',
    warning: 'Avertisment',
    loginRequired: 'Autentificare necesară',
    cancel: 'Anulare',
    login: 'Autentificare',
    openingLink: 'Deschidere link...',
    showingAd: 'Afișare reclamă...',
    youArePro: 'Ai planul PRO! 🎉',
    unlockPro: 'Deblochează PRO',
    proFeatures: '• Nelimitat\n• Nu expiră\n• Fără reclame',
    subscribeMonthly: 'Abonare 5.99 PLN / lună',
    subscribeYearly: 'Plan anual 49.99 PLN / an',
    alertDetails: 'Detalii',
    alertDetailsContent: 'Informații aici.',
    notifications: 'Notificări',
    immediateAlerts: 'Alerte Imediate',
    immediateAlertsDesc: 'Notifică-mă imediat ce prețul scade',
    dailySummary: 'Rezumat Zilnic',
    dailySummaryDesc: 'Primește un raport zilnic',
    summaryTime: 'Ora rezumatului',
  ),
  'bg': AppStrings(
    whatAreYouLookingFor: 'Търсене',
    currentPrice: 'Цена',
    target: 'Цел',
    catchNow: 'Хвани',
    safeShop: 'Сигурен',
    themeSkin: 'Тема',
    accountInfo: 'Акаунт',
    guestUser: 'Гост',
    radar: 'Радар',
    premium: 'Премиум',
    profile: 'Профил',
    profileSettings: 'Настройки',
    regionLanguage: 'Език',
    loginRegister: 'Вход.',
    searching: 'Търсене...',
    warning: 'Внимание',
    loginRequired: 'Нужен вход',
    cancel: 'Отказ',
    login: 'Вход',
    openingLink: 'Отваряне на линк...',
    showingAd: 'Показване на реклама...',
    youArePro: 'Вие сте PRO! 🎉',
    unlockPro: 'Отключи PRO',
    proFeatures: '• Без лимит\n• Не изтича\n• Без реклами',
    subscribeMonthly: 'Абонамент 5.99 PLN / мес',
    subscribeYearly: 'Годишен 49.99 PLN / год',
    alertDetails: 'Детайли',
    alertDetailsContent: 'Информация тук.',
    notifications: 'Известия',
    immediateAlerts: 'Незабавни Известия',
    immediateAlertsDesc: 'Извести ме веднага щом цената падне',
    dailySummary: 'Дневно Резюме',
    dailySummaryDesc: 'Получавайте дневен отчет',
    summaryTime: 'Време за резюме',
  ),
  'hr': AppStrings(
    whatAreYouLookingFor: 'Pretraga',
    currentPrice: 'Cijena',
    target: 'Cilj',
    catchNow: 'Uhvati',
    safeShop: 'Sigurna',
    themeSkin: 'Tema',
    accountInfo: 'Račun',
    guestUser: 'Gost',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Postavke',
    regionLanguage: 'Jezik',
    loginRegister: 'Prijava.',
    searching: 'Tražim...',
    warning: 'Upozorenje',
    loginRequired: 'Prijava obavezna',
    cancel: 'Odustani',
    login: 'Prijava',
    openingLink: 'Otvaranje veze...',
    showingAd: 'Prikaz oglasa...',
    youArePro: 'Vi ste na PRO planu! 🎉',
    unlockPro: 'Otključaj PRO',
    proFeatures: '• Neograničeno\n• Nikad ne ističe\n• Bez oglasa',
    subscribeMonthly: 'Pretplaćivanje 5.99 PLN / mj',
    subscribeYearly: 'Godišnje 49.99 PLN / god',
    alertDetails: 'Detalji',
    alertDetailsContent: 'Informacije ovdje.',
    notifications: 'Obavijesti',
    immediateAlerts: 'Trenutna Upozorenja',
    immediateAlertsDesc: 'Obavijesti me čim cijena padne',
    dailySummary: 'Dnevni Sažetak',
    dailySummaryDesc: 'Primajte dnevni izvještaj',
    summaryTime: 'Vrijeme sažetka',
  ),
  'lt': AppStrings(
    whatAreYouLookingFor: 'Paieška',
    currentPrice: 'Kaina',
    target: 'Tikslas',
    catchNow: 'Pagauti',
    safeShop: 'Saugi',
    themeSkin: 'Tema',
    accountInfo: 'Paskyra',
    guestUser: 'Svečias',
    radar: 'Radaras',
    premium: 'Premium',
    profile: 'Profilis',
    profileSettings: 'Nustatymai',
    regionLanguage: 'Kalba',
    loginRegister: 'Prisijungti.',
    searching: 'Ieškoma...',
    warning: 'Įspėjimas',
    loginRequired: 'Reikia prisijungti',
    cancel: 'Atšaukti',
    login: 'Prisijungti',
    openingLink: 'Atidaroma nuoroda...',
    showingAd: 'Rodoma reklama...',
    youArePro: 'Jūs turite PRO! 🎉',
    unlockPro: 'Atrakinti PRO',
    proFeatures: '• Neribota\n• Niekada nesibaigia\n• Be reklamų',
    subscribeMonthly: 'Prenumeruoti 5.99 PLN / mėn',
    subscribeYearly: 'Metinis planas 49.99 PLN / metai',
    alertDetails: 'Detalės',
    alertDetailsContent: 'Informacija čia.',
    notifications: 'Pranešimai',
    immediateAlerts: 'Momentiniai Įspėjimai',
    immediateAlertsDesc: 'Pranešti, kai tik kaina nukris',
    dailySummary: 'Dienos Suvestinė',
    dailySummaryDesc: 'Gaukite dienos ataskaitą',
    summaryTime: 'Suvestinės laikas',
  ),
  'lv': AppStrings(
    whatAreYouLookingFor: 'Meklēt',
    currentPrice: 'Cena',
    target: 'Mērķis',
    catchNow: 'Noķert',
    safeShop: 'Drošs',
    themeSkin: 'Tēma',
    accountInfo: 'Konts',
    guestUser: 'Viesis',
    radar: 'Radars',
    premium: 'Premium',
    profile: 'Profils',
    profileSettings: 'Iestatījumi',
    regionLanguage: 'Valoda',
    loginRegister: 'Pieteikties.',
    searching: 'Meklē...',
    warning: 'Brīdinājums',
    loginRequired: 'Nepieciešama pieteikšanās',
    cancel: 'Atcelt',
    login: 'Pieteikties',
    openingLink: 'Atver saiti...',
    showingAd: 'Rāda reklāmu...',
    youArePro: 'Jums ir PRO! 🎉',
    unlockPro: 'Atbloķēt PRO',
    proFeatures: '• Neierobežoti\n• Nekad nebeidzas\n• Bez reklāmām',
    subscribeMonthly: 'Abonēt 5.99 PLN / mēn',
    subscribeYearly: 'Gada plāns 49.99 PLN / gadā',
    alertDetails: 'Detaļas',
    alertDetailsContent: 'Informācija šeit.',
    notifications: 'Paziņojumi',
    immediateAlerts: 'Tūlītēji Paziņojumi',
    immediateAlertsDesc: 'Paziņot, tiklīdz cena krītas',
    dailySummary: 'Dienas Kopsavilkums',
    dailySummaryDesc: 'Saņemiet dienas pārskatu',
    summaryTime: 'Kopsavilkuma laiks',
  ),
  'et': AppStrings(
    whatAreYouLookingFor: 'Otsi',
    currentPrice: 'Hind',
    target: 'Eesmärk',
    catchNow: 'Püüa',
    safeShop: 'Turvaline',
    themeSkin: 'Teema',
    accountInfo: 'Konto',
    guestUser: 'Külaline',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profiil',
    profileSettings: 'Seaded',
    regionLanguage: 'Keel',
    loginRegister: 'Logi sisse.',
    searching: 'Otsib...',
    warning: 'Hoiatus',
    loginRequired: 'Sisselogimine nõutud',
    cancel: 'Tühista',
    login: 'Logi sisse',
    openingLink: 'Avab linki...',
    showingAd: 'Näitab reklaami...',
    youArePro: 'Teil on PRO! 🎉',
    unlockPro: 'Ava PRO',
    proFeatures: '• Piiramatu\n• Ei aegu kunagi\n• Ilma reklaamideta',
    subscribeMonthly: 'Telli 5.99 PLN / kuu',
    subscribeYearly: 'Aastaplaan 49.99 PLN / aasta',
    alertDetails: 'Detailid',
    alertDetailsContent: 'Informatsioon siin.',
    notifications: 'Teated',
    immediateAlerts: 'Kohesed Teated',
    immediateAlertsDesc: 'Teavita kohe, kui hind langeb',
    dailySummary: 'Päevane Kokkuvõte',
    dailySummaryDesc: 'Saage igapäevane hinnaaruanne',
    summaryTime: 'Kokkuvõtte aeg',
  ),
  'sl': AppStrings(
    whatAreYouLookingFor: 'Iskanje',
    currentPrice: 'Cena',
    target: 'Cilj',
    catchNow: 'Ujemi',
    safeShop: 'Varna',
    themeSkin: 'Tema',
    accountInfo: 'Račun',
    guestUser: 'Gost',
    radar: 'Radar',
    premium: 'Premium',
    profile: 'Profil',
    profileSettings: 'Nastavitve',
    regionLanguage: 'Jezik',
    loginRegister: 'Prijava.',
    searching: 'Iskanje...',
    warning: 'Opozorilo',
    loginRequired: 'Prijava obvezna',
    cancel: 'Prekliči',
    login: 'Prijava',
    openingLink: 'Odpiranje povezave...',
    showingAd: 'Prikaz oglasa...',
    youArePro: 'Imate PRO paket! 🎉',
    unlockPro: 'Odkleni PRO',
    proFeatures: '• Neomejeno\n• Nikoli ne poteče\n• Brez oglasov',
    subscribeMonthly: 'Naroči se 5.99 PLN / mesec',
    subscribeYearly: 'Letni paket 49.99 PLN / leto',
    alertDetails: 'Podrobnosti',
    alertDetailsContent: 'Informacije tukaj.',
    notifications: 'Obvestila',
    immediateAlerts: 'Takojšnja Obvestila',
    immediateAlertsDesc: 'Obvesti me takoj, ko cena pade',
    dailySummary: 'Dnevni Povzetek',
    dailySummaryDesc: 'Prejemajte dnevno poročilo',
    summaryTime: 'Čas povzetka',
  ),
};

final Map<String, String> _regionToLangMap = {
  'Polska (+48)': 'pl',
  'USA (+1)': 'en',
  'Wielka Brytania (+44)': 'en',
  'Niemcy (+49)': 'de',
  'Francja (+33)': 'fr',
  'Włochy (+39)': 'it',
  'Hiszpania (+34)': 'es',
  'Szwajcaria (+41)': 'de',
  'Norwegia (+47)': 'no',
  'Islandia (+354)': 'is',
  'Ukraina (+380)': 'uk',
  'Holandia (+31)': 'nl',
  'Belgia (+32)': 'nl',
  'Austria (+43)': 'de',
  'Czechy (+420)': 'cs',
  'Słowacja (+421)': 'sk',
  'Szwecja (+46)': 'sv',
  'Dania (+45)': 'da',
  'Finlandia (+358)': 'fi',
  'Irlandia (+353)': 'en',
  'Portugalia (+351)': 'pt',
  'Grecja (+30)': 'el',
  'Węgry (+36)': 'hu',
  'Rumunia (+40)': 'ro',
  'Bułgaria (+359)': 'bg',
  'Chorwacja (+385)': 'hr',
  'Litwa (+370)': 'lt',
  'Łotwa (+371)': 'lv',
  'Estonia (+372)': 'et',
  'Słowenia (+386)': 'sl',
  'Luksemburg (+352)': 'fr',
};

final localizationProvider = Provider<AppStrings>((ref) {
  final currentRegion = ref.watch(regionProvider);
  final langKey = _regionToLangMap[currentRegion] ?? 'en';
  return _translations[langKey] ?? _translations['en']!;
});